[2025-07-04T00:13:08.185+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-07-04T00:13:08.209+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-07-04T00:13:02.950878+00:00 [queued]>
[2025-07-04T00:13:08.219+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_training.execute_training manual__2025-07-04T00:13:02.950878+00:00 [queued]>
[2025-07-04T00:13:08.220+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-07-04T00:13:08.233+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_training> on 2025-07-04 00:13:02.950878+00:00
[2025-07-04T00:13:08.248+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=91) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-07-04T00:13:08.249+0000] {standard_task_runner.py:72} INFO - Started process 92 to run task
[2025-07-04T00:13:08.249+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection_training', 'execute_training', 'manual__2025-07-04T00:13:02.950878+00:00', '--job-id', '335', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_training_dag.py', '--cfg-path', '/tmp/tmpepu6fr9x']
[2025-07-04T00:13:08.250+0000] {standard_task_runner.py:105} INFO - Job 335: Subtask execute_training
[2025-07-04T00:13:08.300+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection_training.execute_training manual__2025-07-04T00:13:02.950878+00:00 [running]> on host d22188e23403
[2025-07-04T00:13:08.412+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Jasjot Parmar' AIRFLOW_CTX_DAG_ID='fraud_detection_training' AIRFLOW_CTX_TASK_ID='execute_training' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T00:13:02.950878+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T00:13:02.950878+00:00'
[2025-07-04T00:13:08.414+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-07-04T00:13:08.456+0000] {fraud_detection_training_dag.py:23} INFO - Initializing fraud detection training...
[2025-07-04T00:13:14.064+0000] {fraud_detection_training_dag.py:37} ERROR - Training failed: 
Could not find `optuna-integration` for `sklearn`.
Please run `pip install optuna-integration[sklearn]`.
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/optuna/integration/sklearn.py", line 5, in <module>
    from optuna_integration.sklearn import OptunaSearchCV
ModuleNotFoundError: No module named 'optuna_integration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 25, in train_model
    from fraud_detection_training import FraudDetectionTraining
  File "/opt/airflow/dags/fraud_detection_training.py", line 11, in <module>
    from optuna.integration.sklearn import SklearnPruningCallback
  File "/home/airflow/.local/lib/python3.12/site-packages/optuna/integration/sklearn.py", line 7, in <module>
    raise ModuleNotFoundError(_INTEGRATION_IMPORT_ERROR_TEMPLATE.format("sklearn"))
ModuleNotFoundError: 
Could not find `optuna-integration` for `sklearn`.
Please run `pip install optuna-integration[sklearn]`.
[2025-07-04T00:13:14.090+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/optuna/integration/sklearn.py", line 5, in <module>
    from optuna_integration.sklearn import OptunaSearchCV
ModuleNotFoundError: No module named 'optuna_integration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 25, in train_model
    from fraud_detection_training import FraudDetectionTraining
  File "/opt/airflow/dags/fraud_detection_training.py", line 11, in <module>
    from optuna.integration.sklearn import SklearnPruningCallback
  File "/home/airflow/.local/lib/python3.12/site-packages/optuna/integration/sklearn.py", line 7, in <module>
    raise ModuleNotFoundError(_INTEGRATION_IMPORT_ERROR_TEMPLATE.format("sklearn"))
ModuleNotFoundError: 
Could not find `optuna-integration` for `sklearn`.
Please run `pip install optuna-integration[sklearn]`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 38, in train_model
    raise AirflowException(f'Model training failed: {str(e)}')
airflow.exceptions.AirflowException: Model training failed: 
Could not find `optuna-integration` for `sklearn`.
Please run `pip install optuna-integration[sklearn]`.
[2025-07-04T00:13:14.100+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fraud_detection_training, task_id=execute_training, run_id=manual__2025-07-04T00:13:02.950878+00:00, execution_date=20250704T001302, start_date=20250704T001308, end_date=20250704T001314
[2025-07-04T00:13:14.149+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-07-04T00:13:14.149+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 335 for task execute_training (Model training failed: 
Could not find `optuna-integration` for `sklearn`.
Please run `pip install optuna-integration[sklearn]`.; 92)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/optuna/integration/sklearn.py", line 5, in <module>
    from optuna_integration.sklearn import OptunaSearchCV
ModuleNotFoundError: No module named 'optuna_integration'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 25, in train_model
    from fraud_detection_training import FraudDetectionTraining
  File "/opt/airflow/dags/fraud_detection_training.py", line 11, in <module>
    from optuna.integration.sklearn import SklearnPruningCallback
  File "/home/airflow/.local/lib/python3.12/site-packages/optuna/integration/sklearn.py", line 7, in <module>
    raise ModuleNotFoundError(_INTEGRATION_IMPORT_ERROR_TEMPLATE.format("sklearn"))
ModuleNotFoundError: 
Could not find `optuna-integration` for `sklearn`.
Please run `pip install optuna-integration[sklearn]`.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 763, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/fraud_detection_training_dag.py", line 38, in train_model
    raise AirflowException(f'Model training failed: {str(e)}')
airflow.exceptions.AirflowException: Model training failed: 
Could not find `optuna-integration` for `sklearn`.
Please run `pip install optuna-integration[sklearn]`.
[2025-07-04T00:13:14.197+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-07-04T00:13:14.222+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-07-04T00:13:14.224+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
